language: go

go:
- 1.21.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  global:
    - DOCKER_IMAGE=bloomingflower/blog-scratch

before_install:
  - openssl aes-256-cbc -K $encrypted_2d8c63ef40a5_key -iv $encrypted_2d8c63ef40a5_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $DEPLOY_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - go mod download
  - go mod vendor

jobs:
  include:
    - stage: test
      script:
        - go test -mod=vendor -v ./...

    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      after_success:
        - export VERSION=$(git rev-parse --short HEAD)
        - rsync -rave "ssh -i ~/.ssh/id_rsa" --exclude=node_modules . $DEPLOY_USER@$DEPLOY_SERVER:~/blog-scratch
        - ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER "cd ~/blog-scratch && docker build --build-arg VERSION=$VERSION -t $DOCKER_IMAGE:$VERSION . && docker tag $DOCKER_IMAGE:$VERSION $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:$VERSION && docker push $DOCKER_IMAGE:latest && docker-compose up -d"
