language: go
go:
- 1.21.x
before_install:
- openssl aes-256-cbc -K $encrypted_2d8c63ef40a5_key -iv $encrypted_2d8c63ef40a5_iv
  -in id_rsa.enc -out ../id_rsa -d
- chmod 600 ../id_rsa
- echo -e "Host $DEPLOY_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- go get -t -v ./...
- go mod vendor
script:
- go test -v ./...
after_success:
- export VERSION=$(git rev-parse --short HEAD)
- rsync -rave "ssh -i ../id_rsa" --exclude=node_modules . $DEPLOY_USER@$DEPLOY_SERVER:~/blog-scratch
- ssh -i ../id_rsa $DEPLOY_USER@$DEPLOY_SERVER 'nohub mkdir -p blog-scratch && cd blog-scratch && docker build --build-arg VERSION=$VERSION -t bloomingflower/scratch:$VERSION . docker tag bloomingflower/blog-scratch:$VERSION bloomingflower/blog-scratch:latest && docker push bloomingflower/blog-scratch && rm -rf dist > /dev/null 2>&1 &"